### PR TITLE
Unit Tests : Added test coverage for RegisterNewVehicle

### PR DESCRIPTION
**Pull request by harismalik-1**
# Description

Added test coverage for RegisterNewVehicle

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by ji24077 — DISMISSED** [review]

**Review by l0minous — DISMISSED** [review]
Implementation does the job as needes

**Review by milan-panta — APPROVED** [review]
Merge conflict with RegisterNewVehicle.java due to carPresenter being changed from private to public. The correct version is public.

**Review by l0minous — APPROVED** [review]
resolved merge conflicts

**Review by milan-panta — APPROVED** [review]
looks good, conflicts resolved.

**Pull request merged**
