### PR TITLE
Unit Tests : Added unit test for the TrafficViolations Activity

### PR DESCRIPTION
**Pull request by harismalik-1**
# Description

Added Unit tests for the TrafficViolation Activity

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by ji24077 — APPROVED** [review]
Seems like Unit test is make sense and reasonable.

**Review by l0minous — APPROVED** [review]
Good job!

**Review by l0minous — APPROVED** [review]
resolved merge conflicts

**Review by milan-panta — APPROVED** [review]
looks good, merge conflicts fixed

**Pull request merged**
