### PR TITLE
Feature: Signup + Login Screen merged into Main

### PR DESCRIPTION
**Pull request by ji24077**
# Description

Created two new screen that allows users to either Log In to their existing accounts via the Firebase Authentication or Sign Up and create an account on the firebase allowing for authentication. Integrated Firebase Authentication + Login Page Created + SignUp Created.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by harismalik-1 — COMMENTED** [review]
Remove the comments in Korean and write the english comments. Needs work in displaying the error messages but overall the code is satisfactory but will need more refinement in the future.

**Review by harismalik-1 — APPROVED** [review]
Comments have been updated, good job!

**Review by harismalik-1 — APPROVED** [review]
Resolved the merge conflicts

**Review by l0minous — APPROVED** [review]
Follows correct coding practices however, files need to be renamed (Loginji.java)
Perhaps some unused import statements can be removed

**Pull request merged**
